# Generated by Django 4.1.4 on 2022-12-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('titleRom', models.CharField(max_length=120)),
                ('song', models.CharField(max_length=120)),
                ('artist', models.CharField(max_length=120)),
                ('opedin', models.CharField(max_length=40)),
                ('video', models.URLField(blank=True, max_length=100)),
                ('audio', models.URLField(blank=True, max_length=100)),
            ],
        ),
    ]
