# Generated by Django 4.1.4 on 2022-12-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='audio',
            field=models.URLField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='songs',
            name='video',
            field=models.URLField(blank=True, max_length=120),
        ),
    ]
