# Generated by Django 4.1.4 on 2022-12-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_urls'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Urls',
        ),
    ]
