# Generated by Django 4.1.4 on 2022-12-15 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_delete_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='title',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='songs',
            name='titleRom',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
